const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

async function generatePDF(user, record) {
  const reportsDir = path.join(__dirname, '../reports');
  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
  }

  const doc = new PDFDocument({ size: 'A4', margin: 40 });
  const pdfFilename = `${user._id}-${Date.now()}.pdf`;
  const pdfPath = path.join(reportsDir, pdfFilename);

  doc.pipe(fs.createWriteStream(pdfPath));

  const pageWidth =
    doc.page.width - doc.page.margins.left - doc.page.margins.right;

  // ========== PAGE 1: ALL TEXT ==========
  // Header
  doc
    .fontSize(26)
    .font('Helvetica-Bold')
    .fillColor('#1a73e8')
    .text('Skin Disease Report', { align: 'center' });

  doc.moveDown(0.5);
  doc
    .fontSize(12)
    .font('Helvetica')
    .fillColor('#555')
    .text('Generated by DermaDetect', { align: 'center' });

  doc.moveDown(1);

  // Patient info
  doc
    .fontSize(11)
    .font('Helvetica-Bold')
    .fillColor('#333')
    .text('Patient Information');

  doc.moveDown(0.3);
  doc
    .fontSize(10)
    .font('Helvetica')
    .fillColor('#555');

  doc.text(`Name: ${user.name || 'N/A'}`);
  doc.text(`Email: ${user.email || 'N/A'}`);
  doc.text(
    `Date: ${new Date(record.date || new Date()).toLocaleString('en-IN')}`
  );

  doc.moveDown(1);

  // AI prediction
  doc
    .fontSize(11)
    .font('Helvetica-Bold')
    .fillColor('#333')
    .text('AI Prediction');

  doc.moveDown(0.3);

  doc
    .fontSize(13)
    .font('Helvetica-Bold')
    .fillColor('#1d4ed8')
    .text(`Detected condition: ${record.prediction}`);

  doc.moveDown(0.2);

  doc
    .fontSize(9)
    .font('Helvetica')
    .fillColor('#555')
    .text(
      'Note: This is an AI-generated suggestion only. Please consult a dermatologist for a confirmed diagnosis.',
      { width: pageWidth, align: 'justify' }
    );

  doc.moveDown(1);

  // Precautions
  doc
    .fontSize(11)
    .font('Helvetica-Bold')
    .fillColor('#333')
    .text('Recommended Precautions');

  doc.moveDown(0.3);

  if (Array.isArray(record.precautions) && record.precautions.length > 0) {
    record.precautions.forEach((p, i) => {
      doc
        .fontSize(10)
        .font('Helvetica-Bold')
        .fillColor('#1d4ed8')
        .text(`${i + 1}. `, { continued: true });

      doc
        .fontSize(10)
        .font('Helvetica')
        .fillColor('#374151')
        .text(p, { width: pageWidth, align: 'left' });

      doc.moveDown(0.1);
    });
  } else {
    doc
      .fontSize(9)
      .font('Helvetica')
      .fillColor('#777')
      .text('No precautions available for this prediction.');
  }

  doc.moveDown(1);

  // Footer / disclaimer
  doc
    .moveTo(doc.page.margins.left, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .strokeColor('#e0e0e0')
    .stroke();

  doc.moveDown(0.3);

  doc
    .fontSize(8)
    .fillColor('#999')
    .text(
      'Disclaimer: This report is for educational purposes only and must not be used as a substitute for professional medical advice, diagnosis, or treatment.',
      { width: pageWidth, align: 'justify' }
    );

  doc.moveDown(0.2);

  doc
    .fontSize(7)
    .fillColor('#bbb')
    .text(`© ${new Date().getFullYear()} DermaDetect`, { align: 'center' });

  // ========== PAGE 2: ONLY IMAGE ==========
  doc.addPage();

  doc
    .fontSize(11)
    .font('Helvetica-Bold')
    .fillColor('#333')
    .text('Uploaded Image');

  doc.moveDown(0.5);

  if (record.imagePath) {
    const imagePath = path.resolve(__dirname, '..', record.imagePath);
    try {
      if (fs.existsSync(imagePath)) {
        doc.image(imagePath, {
          fit: [450, 550],
          align: 'center',
          valign: 'center'
        });
      } else {
        doc
          .fontSize(9)
          .fillColor('#999')
          .text('Image not available');
      }
    } catch (e) {
      doc
        .fontSize(9)
        .fillColor('#999')
        .text('Image could not be loaded');
    }
  }

  doc.end();

  await new Promise((resolve, reject) => {
    doc.on('finish', resolve);
    doc.on('error', reject);
  });

  return pdfFilename;
}

module.exports = { generatePDF };
